[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "18" }
  functions = "netlify/functions"
  
[build.environment]
  PYTHON_VERSION = "3.9"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000

[[headers]]
  for = "/edit/*"
  [headers.values]
    X-Custom-Header = "Skip-Prerender"